"""empty message

Revision ID: bf8c56801f37
Revises: 3074f2c9b6fd
Create Date: 2021-09-18 00:40:40.356364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8c56801f37'
down_revision = '3074f2c9b6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=False),
    sa.Column('mass', sa.String(length=20), nullable=False),
    sa.Column('hair_color', sa.String(length=100), nullable=False),
    sa.Column('skin_color', sa.String(length=100), nullable=False),
    sa.Column('eye_color', sa.String(length=100), nullable=False),
    sa.Column('birthyear', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('homeworld', sa.String(length=50), nullable=False),
    sa.Column('films', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('vehicles', sa.String(length=100), nullable=False),
    sa.Column('starships', sa.String(length=100), nullable=False),
    sa.Column('created', sa.String(length=50), nullable=False),
    sa.Column('edited', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
